export const GET_RANDOM_POSITIONS_START = "GET_RANDOM_POSITIONS_START";
export const GET_RANDOM_POSITIONS_SUCCESS = "GET_RANDOM_POSITIONS_SUCCESS";
export const GET_RANDOM_POSITIONS_FAIL = "GET_RANDOM_POSITIONS_FAIL";

export const CHANGE_MATRIX_DIMENSION_START = "CHANGE_MATRIX_DIMENSION_START";
export const CHANGE_MATRIX_DIMENSION_SUCCESS = "CHANGE_MATRIX_DIMENSION_SUCCESS";
export const CHANGE_MATRIX_DIMENSION_FAIL = "CHANGE_MATRIX_DIMENSION_FAIL";

export const SELECT_ALGORITHMS_START = "SELECT_ALGORITHMS_START";
export const SELECT_ALGORITHMS_SUCCESS = "SELECT_ALGORITHMS_SUCCESS";
export const SELECT_ALGORITHMS_FAIL = "SELECT_ALGORITHMS_FAIL";

export const CREATE_CONNECTIVITY_MATRIX_START = "CREATE_CONNECTIVITY_MATRIX_START";
export const CREATE_CONNECTIVITY_MATRIX_SUCCESS = "CREATE_CONNECTIVITY_MATRIX_SUCCESS";
export const CREATE_CONNECTIVITY_MATRIX_FAIL = "CREATE_CONNECTIVITY_MATRIX_FAIL";

export const BFS_START = "BFS_START";
export const BFS_SUCCESS = "BFS_SUCCESS";
export const BFS_FAIL = "BFS_FAIL";

export const SET_MATRIX_BFS_START = "SET_MATRIX_BFS_START";
export const SET_MATRIX_BFS_SUCCESS = "SET_MATRIX_BFS_SUCCESS";
export const SET_MATRIX_BFS_FAIL = "SET_MATRIX_BFS_FAIL";

export const LEVEL_FINISH_START = "LEVEL_FINISH_START";
export const LEVEL_FINISH_SUCCESS = "LEVEL_FINISH_SUCCESS";

export const FINISH_GAME_START = "FINISH_GAME_START";
export const FINISH_GAME_SUCCESS = "FINISH_GAME_SUCCESS";

export const DIJKSTRA_START = "DIJKSTRA_START";
export const DIJKSTRA_SUCCESS = "DIJKSTRA_SUCCESS";

export const DFS_START = "DFS_START";
export const DFS_SUCCESS = "DFS_SUCCESS";

export const RESET_MATRIX_PATH_SUCCESS = "RESET_MATRIX_PATH_SUCCESS";
