export const GET_RANDOM_POSITIONS_START = "GET_RANDOM_POSITIONS_START";
export const GET_RANDOM_POSITIONS_SUCCESS = "GET_RANDOM_POSITIONS_SUCCESS";
export const GET_RANDOM_POSITIONS_FAIL = "GET_RANDOM_POSITIONS_FAIL";
