export const GET_RANDOM_POSITIONS_START = "GET_RANDOM_POSITIONS_START";
export const GET_RANDOM_POSITIONS_SUCCESS = "GET_RANDOM_POSITIONS_SUCCESS";
export const GET_RANDOM_POSITIONS_FAIL = "GET_RANDOM_POSITIONS_FAIL";

export const CHANGE_MATRIX_DIMENSION_START = "CHANGE_MATRIX_DIMENSION_START";
export const CHANGE_MATRIX_DIMENSION_SUCCESS = "CHANGE_MATRIX_DIMENSION_SUCCESS";
export const CHANGE_MATRIX_DIMENSION_FAIL = "CHANGE_MATRIX_DIMENSION_FAIL";
